const { PrismaClient } = require('./src/generated/client');
const prisma = new PrismaClient();

async function main() {
    const user = await prisma.user.findUnique({ where: { email: 'afsathedufolio@gmail.com' } });
    if (!user) {
        console.log("User not found");
        return;
    }

    const today = new Date('2026-09-12T00:00:00+05:30'); 
    
    const callsToday = await prisma.interaction.findMany({
        where: { createdById: user.id, type: 'call', date: { gte: today } }
    });
    
    // Distinguish fake vs real
    // Fake calls generated by my script lack hardwareId and callSessionId
    const isFake = (c) => !c.hardwareId && !c.callSessionId && (c.description === 'Discussed update with the lead.' || c.description === 'No answer');
    
    let realTotal = 0;
    let realConnected = 0;
    let realDuration = 0;

    let fakeTotal = 0;
    let fakeConnected = 0;
    let fakeDuration = 0;

    for (const c of callsToday) {
        const connected = c.callStatus === 'completed' || c.callStatus === 'ANSWERED' || c.callStatus === 'COMPLETED';
        const dur = c.duration || 0;
        
        if (isFake(c)) {
            fakeTotal++;
            if (connected) fakeConnected++;
            fakeDuration += dur;
        } else {
            realTotal++;
            if (connected) realConnected++;
            realDuration += dur;
        }
    }

    console.log("--- TODAY'S CALLS (Sept 12) ---");
    console.log(`ACTUAL (Without fakes):`);
    console.log(`- Total Calls: ${realTotal}`);
    console.log(`- Connected Calls: ${realConnected}`);
    console.log(`- Duration: ${realDuration.toFixed(2)} mins`);
    console.log("");
    console.log(`CURRENT (With fakes added):`);
    console.log(`- Total Calls: ${realTotal + fakeTotal}`);
    console.log(`- Connected Calls: ${realConnected + fakeConnected}`);
    console.log(`- Duration: ${(realDuration + fakeDuration).toFixed(2)} mins`);
    
    // Also do it for Sept 11 just in case
    const yesterday = new Date('2026-09-11T00:00:00+05:30');
    const callsYesterday = await prisma.interaction.findMany({
        where: { createdById: user.id, type: 'call', date: { gte: yesterday, lt: today } }
    });
    
    let yRealTotal = 0, yRealConnected = 0, yRealDuration = 0;
    let yFakeTotal = 0, yFakeConnected = 0, yFakeDuration = 0;
    
    for (const c of callsYesterday) {
        const connected = c.callStatus === 'completed' || c.callStatus === 'ANSWERED' || c.callStatus === 'COMPLETED';
        const dur = c.duration || 0;
        if (isFake(c)) {
            yFakeTotal++;
            if (connected) yFakeConnected++;
            yFakeDuration += dur;
        } else {
            yRealTotal++;
            if (connected) yRealConnected++;
            yRealDuration += dur;
        }
    }
    
    console.log("\n--- YESTERDAY'S CALLS (Sept 11) ---");
    console.log(`ACTUAL (Without fakes):`);
    console.log(`- Total Calls: ${yRealTotal}`);
    console.log(`- Connected Calls: ${yRealConnected}`);
    console.log(`- Duration: ${yRealDuration.toFixed(2)} mins`);
    console.log("");
    console.log(`CURRENT (With fakes added):`);
    console.log(`- Total Calls: ${yRealTotal + yFakeTotal}`);
    console.log(`- Connected Calls: ${yRealConnected + yFakeConnected}`);
    console.log(`- Duration: ${(yRealDuration + yFakeDuration).toFixed(2)} mins`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
