-- 1. Organisation.deletedAt and isDeleted
ALTER TABLE "Organisation" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Organisation" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;

-- 2. Lead.enquiryAbout
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "enquiryAbout" TEXT;

-- 3. Account.previousOwnerId
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "previousOwnerId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 4. Contact.previousOwnerId
ALTER TABLE "Contact" ADD COLUMN IF NOT EXISTS "previousOwnerId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 5. Opportunity.previousOwnerId
ALTER TABLE "Opportunity" ADD COLUMN IF NOT EXISTS "previousOwnerId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 6. Product extra fields
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isOrgProduct" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "brochureUrl" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "validFrom" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "validUntil" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;

-- 7. Quote.previousOwnerId
ALTER TABLE "Quote" ADD COLUMN IF NOT EXISTS "previousOwnerId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 8. Task.deletedAt and isDeleted
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE;

-- 9. Case.previousOwnerId
ALTER TABLE "Case" ADD COLUMN IF NOT EXISTS "previousOwnerId" TEXT REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- 10. WebForm extra fields
ALTER TABLE "WebForm" ADD COLUMN IF NOT EXISTS "submitAction" TEXT NOT NULL DEFAULT 'message';
ALTER TABLE "WebForm" ADD COLUMN IF NOT EXISTS "submitMessage" TEXT;
ALTER TABLE "WebForm" ADD COLUMN IF NOT EXISTS "redirectUrl" TEXT;
