-- 1. Lead re-enquiry tracking fields
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "isReEnquiry" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "reEnquiryCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastEnquiryDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "lastContactDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "originalLeadId" TEXT;
